import Head from 'next/head';
import { FC } from 'react';

const Home: FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>Hello</main>

      <footer></footer>
    </div>
  );
};

export default Home;
